version: '3.4'

services:
  traefik:
    # Use the apline image, its lovely and small - 22MB!
    image: traefik:1.7.3-alpine                          

    # This just exposes the ports to the host, the host firewall is configured separately 
    ports:                                               
      - "443:443"    # Expose HTTPS port (and available externally)
      - "80:80"      # Expose HTTP port (and available externally)
      - "8080:8080"  # Expose port for the træfik UI (shouldn't be available externally)

    # This is the network which traefik uses to communicate with other containers
    networks:                                            
      - traefik

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock                       # Required to talk to Docker
      - /root/traefik-swarm-example/traefik/traefik.toml:/traefik.toml  # This is a volume mount for the træfik configuration (see line 18)
      - /root/traefik-swarm-example/traefik/acme.json:/acme.json        # This is used to store information generated by LetsEncrypt. There is
                                                                        # no config for this, just touch a blank file  before starting the stack.

    deploy:
      placement:
        constraints:
          - node.role == manager  # Only run this on a swarm manager

# Overlay network definition other apps will use this to talk to this service
networks:
  traefik:
    driver: overlay
